# Generated by Django 6.0.1 on 2026-04-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_trending',
            field=models.BooleanField(default=False, help_text='Show this product in the homepage trending carousel'),
        ),
    ]
