# Generated by Django 6.0.1 on 2026-04-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_is_trending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_trending',
            field=models.BooleanField(default=False, help_text='Check this to display the product on the home page carousel'),
        ),
    ]
