# Generated by Django 6.0.1 on 2026-04-23 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_variantattributevalue_attribute_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Color, Size, Material', max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='shipping_returns_details',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_fit_details',
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_and_returns_policy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size_and_fit_guide',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PropertyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('hex_code', models.CharField(blank=True, help_text='e.g., #FF0000 for Color', max_length=7, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='shop.productproperty')),
            ],
            options={
                'unique_together': {('property', 'value')},
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_quantity', models.IntegerField(default=0)),
                ('images', models.ManyToManyField(blank=True, related_name='variants', to='shop.productimage')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='shop.product')),
                ('values', models.ManyToManyField(related_name='variants', to='shop.propertyvalue')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductAttribute',
        ),
    ]
